apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: gke-pingpong
spec:
  ports:
  - port: 5432
    name: db
  clusterIP: None
  selector:
    app: pingpong

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: gke-pingpong
data:
  init.sql: |
    CREATE TABLE pings (
      id SERIAL PRIMARY KEY,
      count INTEGER NOT NULL DEFAULT 0
    );
    INSERT INTO pings (count) VALUES (0);

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-stset
  namespace: gke-pingpong
spec:
  serviceName: postgres-svc
  replicas: 2
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: config
          configMap:
            name: config

      containers:
        - name: pingpong
          image: postgres:alpine
          env:
            - name: POSTGRES_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: pingpong-postgres-key
                  key: DB_PASSWORD
          ports:
            - name: db
              containerPort: 5432
          volumeMounts:
            - name: config
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
        
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: gke-pingpong
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Mi