apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong-app
spec:
  template:
    spec:
      containers:
        - image: PINGPONG/IMAGE
          ports:
            - containerPort: 8080
          env:
          - name: APP_PORT
            value: "8080"
          - name: PGHOST
            value: "postgres-svc"
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: pingpong-postgres-key
                key: DB_USERNAME
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pingpong-postgres-key
                key: DB_PASSWORD
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              cpu: 100m
              memory: 100Mi