apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-dep
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcast
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: broadcast
    spec:
      containers:
      - env:
        - name: NATS_URL
          value: nats://my-nats.default.svc.cluster.local:4222
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              key: DISCORD_WEBHOOK_URL
              name: todoapp-secrets
        image: BROADCAST/IMAGE
        name: broadcast
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 1m
            memory: 1Mi