apiVersion: v1
kind: ConfigMap
metadata:
    name: private-key-configmap
data:
    private-key.json: ENC[AES256_GCM,data:CagaXLcnTHefslSblOpmuTLSsbDETLmrJ3qp3f5lv//+3UFKk/KlD3K7VEEmr7sFQuIl8ZTvZXifqeuxNyRYFtYqQhcIZirU3t7RL+G8ifRQiX3psWmvMjmrIFo2TKhedEvpow0hxtgPIGIyj8Lgc1KikqavNT1BAro8rP7Ek2etZl74DBcLAWM8sP9v0bUBEuaWnpNQ+m8qE1Lce+1nFF3defWdG/qHx/U6X1ggYv79ImunTOA8Q+Fko/qdishoPdHYjm4vYb9iyW1Bl4jPnDBBimfPr3e9LwrRsRqagZd06U6osKA9GGULHd97uRDxxsZSEKtT9Pk6aAn71UxahqAfl5gJkuKo+Ao47yJ2RvhSINoZIjSgFC64MW2wV/+b9lCahu8GVeJVqVb6ZScvT+fuaptA8mKir7czIoTnAEdR6a8R6QuMyjP7pwVmr5H+blYW3/PpKJDTDVSoSTGV+N2sVrvg7voLdNXdy8Uu6TRNDDzEFqKZehc+frC9NkYyivhyiakeUX0CVjtQCmt4xGk/L7ywwu23pqCgS5KKetJyqfDtaWz7pvDhHZbDeZ5ypvp0AM9AhyaeWSd8zSyMN3LEZXkevQUzhXhdhs/kZIzuLixEMTRSatAJB5x61USGHpcgJc0oDPa+xGXKCg0enBjRhouEBmcLw48xjGSoX6SpbbOcCMm8n9EN/ZgkOCO1Kqs+qDxeLPOFvNPjKOlhVx4NBbq9bOaBvtpXHbe2LYIzOnMChjxOrUX/wDmdUlncaJm0iXY6svQWBK7NCb0ny+MO5OG2lAl97TLTFpaGkbBu9U7U4m0MOuMJEROJmMoEkt2VINJ0QUWk5U5Rkq/sd3FHbfsWmecv/SXM4QrhupBKi19pNr9kIQgavb8IsoSRp1oZub4QHwkZA6wjABpl9VTCTPEIeYTs3WCQ2agVY09H2yqT67OKbrgIdHGNnb4M1VAjepKx6oATS6OuzlsIke4XydQFFVshexcPM1oEx6FoSEPYssNgmw1oZspRZ5/KtO7d9jq37NnkOwfgDaNzpfeGBML18mgxEt4aut43Hx6EvYbtL8xUHei5EDhAck01Z6IQ/4g5bNAAqv/N0DUH7vwQ8GGWHGRFeRgtoB4a8tTP8CIUHkiWLMTMGLJ9pUgKid/wP0+mjNA196tKvPLIge17dxulTL+Dy4F/GR9ehYUQr+kopuFEyezrqLNnpmo/S+Jqwc6oMO7p+AJ/VCih8a9FuniXPJ0VAD5K0kparBpYlDFhMvYSVYKqMyk9idPHFdVuGHVI82sFUZEgLoAyNiPYSLKNuQAj1IoU4MjqBM7t9DYQqwiAGgNCqkKG5cRUAWqSzdc5hPEdW2nk4vRLpWQRa9XsxgUcnetXck2kKRBHwyARcOTLHBVtT9Gn2xyDpQ3/EjXIKjaZmUvPVzpiL5WcTXFlCW7A7JevkeIDXnlL+ZY6T3bT8HA74mmnllTvxQ6svcSzaghpzm7CXoD0pJNY9izC+RjILFEuMGPpN9pMngJuMb3YnbGlson0BIspSdJ0rn9TXc6wE0dTsgWhvwFtHC79SXcW1uQU1Nzbowl1yRAnwouOj0r+XkKBatUvV/+0CX2TE3NqiX4a9DWbNR2p7+Yy4GdCq3/8QY8qyxRmHXAKnE6qJemOLPHCVQLCKTulO75BjkiqTY/4wYb6wJjvn9OQVcMva46bPLbMnamtMVUMGSz/Zo6C1vXTXzCO/xffH/jf0nRVOWCcvqkq26FAaNaVg5Yiz0t9bGrUw+GVQOJmbRSYWKud9qbURSXbSYWapOegNwnix5WMO5gba2+JZfQqdxvJXfblULxqT1M3mvMHs9iOezQmtiir1zEzySsl4sYwCNefn+T5Nw31CTzJUuPtSKoStfu5fMNBX95xxw+TgSAQnJem0A02IRAWUWiZo887yk9vzTIxUNrs2jGxlcriam4YRG+E136T2pC2OMzY/iiO8HOt9sfkrMZF3oKqYs6OCDXSVP0n5k2z50vU1zcF9/nbLbD05MWdrpDm0S7JSSP/UTLaU086roUVFMOqWidCdBCLicc7RXHVILO4kjVCyCSL49tm+faRWb0/giWKiEJT8wbU3K7A9NGNEB2bSTFrf3FH1ZLmTYkIrnVkBjkCXz91QcA2M7gdjMhFMhFoT04rcAdXDsXTIr79b+884jKzfRHgYLHc7r154RhFWG/7fL/xi5UtRiWdBtYkjBvsTIv7YlMrGgyNtJWBFh6F05Z1poX5WtVI1qZk879c0Wjmoy8lKYSaeHMpNwEYESWMrG3RUGOTkjJtC1wHKKeomdMXCUSU4xHVMunoOBP5tqMp/v/KbPf3t6CeYyud9otOysvbAvxhWoVgnOyKSgLj5YdzdTtw/hNbDSmRqMiL1mA/K61cuwqSdoWgkiEXQseWx/cRABjnsW0ghq76i4Jt94XmRoOljoBhOUoUIlhDm4LETspWBQ4DHSKOrQ0VW6Cmt39nrriUFpUh6zJcROls8iFMUEATC+wJSHFFQYfKL6HdVI7HeXOyLxYcwQA6rCwUH7oxtnNBxS5wioOEY83ef2SDZTdMzjpQI5VCGODs3mT1f9Qw2knxsz54KZk4t/4PNEyQFkKOqkT5wz69hxh41Ra9uhNLinwZh5N6lyulYC9/6y1yc6TrnFRJ8Zrxi8ns3mES+k/SzFgm2M7054v3djUsEJW9hM58dwtQS+vZkAc05PtenapZfwUw6ucqJ1qULwirx+7C4bOUGSTsNXetlwNRd5MAPHniQos9YeYv2YwMrO5Rg88vy9AgmIq0klJuJK3Vd2cbFAxApGCUFV4H3+SUBKncfq7sg1fdc29aBqLdpcL52p901rZZYlFvUvy87h+Lf2lywKX7tyLZpflBBp7J2PUnhCnIjR9FqHqD7usCtVKFVLG2hUlvGHhZuXqD+BTZ1B6b6SXJzgHFXSapl0NI7A9nCO8nZ2vx1PMbc+7TzLvI2kV/7xinzb1Iij8VXkKpjCZouifw07BjQNsSmhJwH2FsTZlYH8F+uaiA0EujRYofKm1zWXGZI0nmXWZVPegu2BI9xkm96ahrD+Gh7NQt3+iWFUWO69NaYWIEY9jrE+KHryZNJksYNDyoM4trCN1vS9QL3Jj/2eKSJbrC9gzY/bLZdm9dlcjo8Rg5xyuP1idKs48nz5ZzGsiFDQlbIh3q,iv:tCGWqhY3Pv1pLAUaYW9zIOsO+otN/Jo+DWDG3uwy8Vw=,tag:Uo7TamzguImdIYNGv8WHAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17zz5pz4u5h7jga6kvc7h6xad2uc9w6jhtjeu5kv8pv2t69p7xcwq6cezvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN2dOcW02bjZBNlZFWk9n
            WGJzQytSMnk0eFFwbmoxNlZ2a3NOM2dJRVRjCkRkSjJRejRwVW15dmRvZGhkSHor
            U3d5a01QTUFLbmw1WGt3eFZxTTBvOFEKLS0tIEkvZm1JcG9uZ25keHJjeVN5Sndz
            amcvY3d5aUhqcmVUdEpPQTN0dHBndlkKOixj2fDW1HRqQoksY+FnNhEbQbejk3nc
            6WK+XX3cMuRAtdSlLpj3Jg5OaIV6Ai8Txj4Wm80DjAEsHYzP1OC+Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T21:26:53Z"
    mac: ENC[AES256_GCM,data:vy6FIxQXQ1wiqEETpuFQJ/GvcOQhp9UerFcNBFFhiHuIFsT9B0EXv9V6R3bOWz93G5zsyaEfOLV+vmWLJzadG6X3FNT97tiJhf1HvxhlCWf20i5ZTiRDkQU9fG9S0PuwHiVnnfLxjhcnXWzeYSb1uB6u+siEdQrD0rLkxdWAc0s=,iv:+vOxFcruv+3mKV8xf9lmiKSu0f+AvGnkndGJWkbcZJs=,tag:vbYtIQUMq3TYkSAIIe1ZeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.2
---
apiVersion: batch/v1
kind: CronJob
metadata:
    name: backup
spec:
    schedule: 0 0 * * *
    jobTemplate:
        spec:
            template:
                spec:
                    volumes:
                        - name: private-key-volume
                          configMap:
                            name: private-key-configmap
                            items:
                                - key: private-key.json
                                  path: private-key.json
                    containers:
                        - name: backup
                          image: your-backup-image:tag
                          env:
                            - name: POSTGRES_PASSWORD
                              valueFrom:
                                secretKeyRef:
                                    name: todoapp-postgres-key
                                    key: DB_PASSWORD
                            - name: URL
                              value: postgres://postgres:$(POSTGRES_PASSWORD)@postgres-svc:5432/postgres
                          volumeMounts:
                            - name: private-key-volume
                              mountPath: /usr/src/app/private-key.json
                              subPath: private-key.json
                          resources:
                            limits:
                                cpu: 100m
                                memory: 100Mi
                            requests:
                                cpu: 1m
                                memory: 1Mi
                    restartPolicy: OnFailure
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17zz5pz4u5h7jga6kvc7h6xad2uc9w6jhtjeu5kv8pv2t69p7xcwq6cezvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN2dOcW02bjZBNlZFWk9n
            WGJzQytSMnk0eFFwbmoxNlZ2a3NOM2dJRVRjCkRkSjJRejRwVW15dmRvZGhkSHor
            U3d5a01QTUFLbmw1WGt3eFZxTTBvOFEKLS0tIEkvZm1JcG9uZ25keHJjeVN5Sndz
            amcvY3d5aUhqcmVUdEpPQTN0dHBndlkKOixj2fDW1HRqQoksY+FnNhEbQbejk3nc
            6WK+XX3cMuRAtdSlLpj3Jg5OaIV6Ai8Txj4Wm80DjAEsHYzP1OC+Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T21:26:53Z"
    mac: ENC[AES256_GCM,data:vy6FIxQXQ1wiqEETpuFQJ/GvcOQhp9UerFcNBFFhiHuIFsT9B0EXv9V6R3bOWz93G5zsyaEfOLV+vmWLJzadG6X3FNT97tiJhf1HvxhlCWf20i5ZTiRDkQU9fG9S0PuwHiVnnfLxjhcnXWzeYSb1uB6u+siEdQrD0rLkxdWAc0s=,iv:+vOxFcruv+3mKV8xf9lmiKSu0f+AvGnkndGJWkbcZJs=,tag:vbYtIQUMq3TYkSAIIe1ZeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.2
