apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-staging
resources:
- manifests/namespace.yaml
- ../../base

patches:
- path: manifests/ingress-patch.yaml
- path: manifests/deployment-patch.yaml
- path: manifests/rollout-patch.yaml
images:
- name: APP/IMAGE
  newName: eeritvan/todo_app
  newTag: 756915951e3087b2c56dd495e096989445fd48f2
- name: BACKEND/IMAGE
  newName: eeritvan/todo_backend
  newTag: 756915951e3087b2c56dd495e096989445fd48f2
- name: BACKUPBD/IMAGE
  newName: eeritvan/todo_backup
  newTag: 756915951e3087b2c56dd495e096989445fd48f2
- name: BROADCAST/IMAGE
  newName: eeritvan/broadcast
  newTag: 756915951e3087b2c56dd495e096989445fd48f2
- name: DAILYTODO/IMAGE
  newName: eeritvan/daily_todo
  newTag: 756915951e3087b2c56dd495e096989445fd48f2
- name: STAMPGENERATOR/IMAGE
  newName: eeritvan/image_generator_app
  newTag: 756915951e3087b2c56dd495e096989445fd48f2
