apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-staging
resources:
  - manifests/namespace.yaml
  - ./../../base

patches:
  - path: manifests/rollout.yaml
  - path: manifests/ingress.yaml
  - path: manifests/deployment.yaml
  - path: manifests/cronjob.yaml

images:
- name: APP/IMAGE
  newName: eeritvan/todo_app
  newTag: test4
- name: BACKEND/IMAGE
  newName: eeritvan/todo_backend
  newTag: test3
- name: DAILYTODO/IMAGE
  newName: eeritvan/daily_todo
  newTag: latest
- name: STAMPGENERATOR/IMAGE
  newName: eeritvan/image_generator_app
  newTag: latest
