apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-staging
resources:
  - manifests/namespace.yaml
  - ../../base

patches:
  - path: manifests/ingress-patch.yaml
  - path: manifests/deployment-patch.yaml