apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-daily
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-todo
            env: 
            - name: REFERER_URL
              value: "http://todo-app-svc:2345/staging"
            - name: TARGET_URL
              value: "http://backend-svc:2346/staging/todos"