apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-backend-dep
spec:
  template:
    spec:
      containers:
        - name: todo-backend
          env:
            - name: ENVIRONMENT
              value: "staging"