apiVersion: apps/v1
kind: Deployment
metadata:
  name: logapp-dep
  namespace: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logapp
  template:
    metadata:
      labels:
        app: logapp
    spec:
      volumes:
        - name: timestamps
          emptyDir: {}
        - name: config-volume
          configMap:
            name: logapp-config

      containers:
        - name: logapp
          image: eeritvan/log_app:latest
          env:
          - name: PORT
            value: "3000"
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: logapp-config
                key: MESSAGE
          volumeMounts:
          - name: timestamps
            mountPath: /usr/src/app/stamps/
          - name: config-volume
            mountPath: /usr/src/app/config

        - name: pingpong
          image: eeritvan/pingpong_app:latest
          env:
          - name: PORT
            value: "3001"

        - name: stampgenerator
          image: eeritvan/stamp_generator_app:latest
          volumeMounts:
          - name: timestamps
            mountPath: /usr/src/app/stamps/