apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: logoutput
spec:
  type: NodePort
  selector:
    app: pingpongapp
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpongapp
  template:
    metadata:
      labels:
        app: pingpongapp
    spec:
      containers:
        - name: pingpong
          image: eeritvan/pingpong_app:latest
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /health
              port: 3001
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3001"
          - name: PGHOST
            value: "postgres-svc"
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: pingpong-postgres-key
                key: DB_USERNAME
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pingpong-postgres-key
                key: DB_PASSWORD
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"