apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-production
resources:
  - manifests/namespace.yaml
  - manifests/broadcast.yaml
  - ../../base
  

images:
  - name: BACKUPBD/IMAGE
    newName: eeritvan/todo_backup:latest
  - name: BROADCAST/IMAGE
    newName: eeritvan/broadcast:latest