apiVersion: v1
kind: ConfigMap
metadata:
    name: private-key-configmap
    namespace: todoapp
data:
    private-key.json: ENC[AES256_GCM,data:fpM7QXwOrfCaASUFZPNPhDLXFrz9qu3H7SCJ6aMy3Xdr5QeUUX8eK+8C2AmKDDGR2ca4/i6ZO7nUzY2qXTyKdqEN5sHu9hFP/IhDLXZ+26Jow+zXIDqrnSUaTmO393RJ+rgZ8T54ItTW2Kq7SPdBS/iF9J8K+2548xU0yWfkwxPWU4iS66UtvMG/JHQtl7OsjgMCJGM/1E498quYPLzXjACDtZGoO6PoPsdRed+lEnuVBxZyHDMPERwHXPciJE1g0e8GzZWidhA2OPKE/ZPdKU/bWemRP3WlYv6Pvu0sVk3cbcl/Zcjb1vgQD9N/Rq/SYCun0xMpSe8iaskhGgg4wcFY8YX2RiI4Qw1akMJmIRA3EZOpTGBf1So+BughybVh4cxaF3JvrvdjGPMClDTzQc2hQEb6zH11j8GfFY87x7+nL+4XyugjRL8PPv5H2WX8a7XVWHtyZt9X/C6WH585aKPmMrtTnr/8g6/YAEoED2FYMgYjbYeZv/WQAsWomrm4OGNW/8a4QMrx9vIUfUbsFx9L75lEIVvW8uXbp4yYS/SumJ1/5HyJ+aVIyWSbeF+8JoE1l4Xeye3/j6s35HamrNjWJDOuleJiggAy+5n4ELwWkny8BknyIBmgfG9g2feH73gZBNS12LqqiwThdaky8InhmOtxTbJRcW6L+cKmpat8la84GHAupLK37sR3wzyiW5+6yuQpB4SpcyaaRo20crKTnvIqpFnmSPkKOiZuxoNhGX50iGB6mxa9VWogbzlQEI1cHCZt09JCUKkjNQ3wP9T+9Yk9NDqjC8THKHekag3al4vuSyllAYYk/lEqT9p4xp1nuq1fx0ZiaYAsBKPlRl5cnX6PmFYkYUnSYARRXuSlTFdcFq0U9lV3W0jCRxbOnmVyYpqQTrf65LtiM9yURs1C3FojMVlbV7m+JHbsxWe7zVFcD7M2NGJANFJTHu+roBHHd/wLcAt8l4udcb+HVbz+nBDz6doVoElmWI6FFed1JqGKSNjgTDUt/fp9/YTHyESucqVhKBHb+/RSGWXsRMMSknGNJ+Nt56Kr8Cs5zs23VKlWrrBMTA4N2NGs/kHc0w4kbqGqGtewfZ1+mx3enPA3t3R/MHwBBLtvbjiXNLNSsNx7cG5JsdX2pyQVWqBQopv6L+SDgVEwyn7iDNuVtkQRvHENj5UN1+kAgmysBnEYxIoBuHLVtFz7csQ46lpHy245t1HM6YAD2/ebJozsCqCgY4NnukzOuIF0aivMdNBEWVjSoOMuGF3fumomGHwfLCKXdPmwe5397RhKIull4YQuvdmj5sp7X3D+2kqk5s740k2buWyBNFdMeBHdKdF8TVez9cUhsgzvw3GSpx1WuxZo08DTj2uVKsIY0aMXWI/9Monovp+aGzgG7hzVQK3Afjg1qDcWmLBWLfBm24qZbHwQHeISsAH3vbyU3U52xMaVgfAonMw394cJL/UEGqI/5ZykuhejbusFXR54Q9AxM3P9sFTH7c4/37V4GgOIv1La7m2ECzIPFVYJ3T8/dK2yBI7WlZ4flkVc6GPIvQHcA4z62JElVBr+1nW19F2GxmhFo+SC6YuqFq5rEKPKTZ29N7pGONlPMDi5KYRyk9C/nLTMv4sSiuvwGbYCOT1gJFnk1YuXJfwQmlBDwhsICDTwsdUGUTayU+QD9VibRwbgbSG5rcDxGSzmNxV4T3vHeWlRQrd5FifRbWcK32Lb5VJ+sKVfylJHugPvkBqgjbTXwnffxBnoRaMeE/cXQ3ybpPhnMZfRZhYhj2rOspeI2TbH7QumeA3ntGOkaO+c3eWG8kKP3uA+ymjnGZ2AsIn58oDiyAnNAO07AYjJPuuzNObetJwnW8NZVBiSRDrMkouSEqwMc2rW0JwdRziMBqNM4UMoj4GqGfTFjIXwyTOibFtCf8YPoWGk6fDfDR+YAxktZDiw+ZObi6xZ+rxL99qVBFZhuXGqG9YPvqVmc54cJ3Ig8rc/wXIt/7H6OpovFN7qEVQ9yBN2G8WaybDK4AX09YwAxLzXwePGUbtxPIpvPNfG64gnH0UH3CoDVNfljOW4SRkdS2e8vxbp1kmCZ+rNhiZe0Z3FzImwzvstfb8pCvoJes/93U1Zre/CuBrFV1dU76LskhtPJMj+Y28tIie9Ie6VKinDrrJ2nWkXe81Nl4j6Io+vl3cN8GwoJzOHzH7zcybpYS0nG2UEh7j2gix66fwhK+Ulq9OzKMX8VNIO2u4ZmBC3D9wmZ/ZcQeWb/WuEW/fJmeQ8ypbWIsgumpW+uu+ymNxR4uKUklF2EYRVvDw7Dg5OnbmUrnoA2OA3AViRksrcW/gJB4fQ5tjMjCkegmGs2rU9BDR0FYsuCxI0QibkIfvdNsA4thnP/cAPcuQlHoKcGxuEyqB3a/odSXz+XILmFoks4AFYiU809ttzYZKmK/DXmOc3sucsZh3gWhBGE+uumxDRJ4AzbTvoykMW158+3lmutmOovvYkVLkKIvJ8KfcxgfTgmPLSQUQsRXNOnPW665ymyL4Ds6ukaxZHD9cXFDvAc2r85xzrrKSGCmpHRSxGVmUtjWQCG5sNhLvrauik6I1cdagaRf+wlsieDGP9FdV56478BmB26FvpaNWqTIjwh7jfvTLJFBOnDV450jOD/AFdJMwk3DeZCOfCLlvRy6EUUxlOTHfizkOcNJFYcK0n1dkuLz+4cjUuSimmMLPBetvfN8eCcZMoe4/hz/OxsCdzBIVDgULozbJaKT6SlaH0o2NicX46pAJ/hBAnvUwc831bO1hAwcf2Yq1IByVEtxq5uOE6WmoBY4gPI7sRHz8NoEYffG6721ObIRT2XjqHfgI4FHQsfwF/EAEM20Pi9qf5uvbG5w3rhz+lkdbyJzZ1Uexvygcy7lvgmT7pLOkEUrF73d3COYsBsqU6rV4qFhOhH2UKo0gIi7oJoc9Y4ryBlhL2o5B4Q0v2B8RJFAdFGX9Tsj70wBrlnuQn17Zd6nJu6qOsSilZC7yQXEVcXUS0blr56SgI7XIuUaI/XC7Ztot9v9tWhc5CZdP6cwEerE2DzyA+bKvkX3Bpf8pfNzSduZDAHEvqDASYBBnGRH04W03aSIgAq73mPqGLRMVqa5bwA0tSGoB4WRX47IVb2lFjwZ3jc4DLaIUn+2wCpa+WnK1OZcxeka/yXdwIrJuuXDQ7ykzz,iv:6ZUCVxvdP78FwZMYZYNufqdWS2Vt9OJ4uDRJLsYIKbg=,tag:jrmql16iFfTpbpGOtXH4Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkgrxnl6lwkytr55407y0ka4f73zl0rlyzmjtxsryqczq3n9rvss2p6dcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM29VWWVER0t3SHRGaENu
            L0pYZmYyMlRzMi9EcTVmaktXVjdwaThxVkRrCmFDVytEMWxCVGhoYWFSNW9SN1JC
            Y1BUZG90eUFZQW9OMjBwa0NySjBqdUUKLS0tIExjeElPaDZQUXk2TG1tSXgyVzZj
            cW5pcTFKR1BuYzg4a3hneGtxcHcrUE0KdaY0OPvr6MZHc0lO4FMXlX+7z8uF5jA1
            0oWH3IkCC0z8yhIQOa1Gy78gkxWecl7J1ZzAdmv5m0XTAfkFSFjk5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T21:44:10Z"
    mac: ENC[AES256_GCM,data:bOywi+dpirKyRf60iKtV4E1T1st4fUGJe621gN2QTkxUQIOGRn6Pfr0ukAJKadG3J7I+iBfyq2A8V1ICbOJ2HPa8FYf/nTDRhBv9OR4nV4QIGPVP94fMPahpCuwwsTMN2wAcr1nJzo825tsMDw8zOfi1pPAXVHpBpKRhd0+kQpU=,iv:tzWYiJk/pTyWTEtZ+TnhJ1xB6dQWGlq6Xhzvgw0xJyI=,tag:7Blj/qOc0CcrGRK05Rjp+A==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
---
apiVersion: batch/v1
kind: CronJob
metadata:
    name: backup
    namespace: todoapp
spec:
    schedule: 0 0 * * *
    jobTemplate:
        spec:
            template:
                spec:
                    volumes:
                        - name: private-key-volume
                          configMap:
                            name: private-key-configmap
                            items:
                                - key: private-key.json
                                  path: private-key.json
                    containers:
                        - name: backup
                          image: BACKUPBD/IMAGE
                          env:
                            - name: POSTGRES_PASSWORD
                              valueFrom:
                                secretKeyRef:
                                    name: todoapp-postgres-key
                                    key: DB_PASSWORD
                            - name: URL
                              value: postgres://postgres:$(POSTGRES_PASSWORD)@postgres-svc:5432/postgres
                          volumeMounts:
                            - name: private-key-volume
                              mountPath: /usr/src/app/private-key.json
                              subPath: private-key.json
                          resources:
                            limits:
                                cpu: 150m
                                memory: 150Mi
                    restartPolicy: OnFailure
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkgrxnl6lwkytr55407y0ka4f73zl0rlyzmjtxsryqczq3n9rvss2p6dcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM29VWWVER0t3SHRGaENu
            L0pYZmYyMlRzMi9EcTVmaktXVjdwaThxVkRrCmFDVytEMWxCVGhoYWFSNW9SN1JC
            Y1BUZG90eUFZQW9OMjBwa0NySjBqdUUKLS0tIExjeElPaDZQUXk2TG1tSXgyVzZj
            cW5pcTFKR1BuYzg4a3hneGtxcHcrUE0KdaY0OPvr6MZHc0lO4FMXlX+7z8uF5jA1
            0oWH3IkCC0z8yhIQOa1Gy78gkxWecl7J1ZzAdmv5m0XTAfkFSFjk5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T21:44:10Z"
    mac: ENC[AES256_GCM,data:bOywi+dpirKyRf60iKtV4E1T1st4fUGJe621gN2QTkxUQIOGRn6Pfr0ukAJKadG3J7I+iBfyq2A8V1ICbOJ2HPa8FYf/nTDRhBv9OR4nV4QIGPVP94fMPahpCuwwsTMN2wAcr1nJzo825tsMDw8zOfi1pPAXVHpBpKRhd0+kQpU=,iv:tzWYiJk/pTyWTEtZ+TnhJ1xB6dQWGlq6Xhzvgw0xJyI=,tag:7Blj/qOc0CcrGRK05Rjp+A==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
