apiVersion: v1
kind: ConfigMap
metadata:
    name: private-key-configmap
    namespace: todoapp
data:
    private-key.json: ENC[AES256_GCM,data:gv7uI54ofM+GR28IQWxR77RQFN7kAiuJMzonRwZw0BD0R+BI16wqGVf/5diKqaILiHd+73vkkmd8+MPLBEVs+NyvUY8X+2KKO6FEVHxtaajluRpoPUnSocHU7ZjXWbCYFpdXESeQNIeCtLGbHCw8Yutp6gKrE2c6KvxhntFpeNQe6ucWXwGO/XcypUUQ4THc7AfPkhoh/DPP0QbUFeWZmKbU2N7yGoyUv0kgOw7BEqx8op04RQhvTY6ilQCVCvCTxzC+sZr2YufQszmrg5Ujyp4CGHTSWDIin8HoJ44WyisK7BaO5z+17QM9+/JgIeaC5Y2HcNstZYvnkAQuqv0Bu3EIbSY+UXW+GV+LXLfkeCyjYLo4BbjUvXFdLV4G8OU/Ev2r/4UBPXevxZZWLCpvT0hyYsX2LHgJ8Qi1lTnTNyN5hXhRuJZQjm7PFAbzJr+6f7J5wywvYHzEg7wthUQz/M7bLQ6WysuolC65JaBJzSK4oxlh9VVrHRQeDXGXjDyAM/tiMvtPmhLqhqdprrM0NtlCLVFE8iSFGa4Qu9mXOtdVWngN3xkZQ8Yqe/I+YBWXbn9y05E+IbiZKKNkWfLqT35q09eUx3+pa7T6VZRtc2MX+uaKp6Ci3zmThkaM5EOyaLmheTeSAQwaLm/92xKr6hH96V0fAmhGz9H21HOszMcy+lv//TqBhPy3VIFisF0Z+6Q23NjtpLviHsQAfbqYY3PlnHqd9Jqer5rwzblrfzlyAjuiP+M+URzrOmultXBNcoG6dl8B6VGbva3u2q4Vt5HmlZxO4Z8HN7eyqSxsOqOrvd9wk1cusKzO1jupJ+PRJeu8w9k9ShOD99Zw+fT3TAWXMQgrhPxwyJAW6FN90Whtv4nP7A9+oEUgM251oX+Gf7beFm+9URQu/uLb3Q9EmQXb2XSB5e5z2mlBOI6f6xw0jfvz94tKQw1vgFqfANiB/FLXpdcBghcRCfKvX/RjTAsGul/PlFCAY5XveiicYUb9CKaI9Ns+VwjPRs75RC/W61WfoPvyUTYY+6xhKDnJtZIeOqq4VwtkFhfCFTpVcWqCRuUF4nv/gixTQeohueFWLHG4qVLri/3Iz8kFT4Q+HW3eHAyro90S3J3+zQcH3l021zhZw0xQxhiwI8pcOwkkHP7WMeFS3QV9byuwshl09XHcBvtSjC3PSuhh/BYA6xe3YYyonBx/ZfFfodx/esIZ6p+qQL8SHFXDocjAPaI96IvNqMPVqHoYhO4Prk4argL++PdTsVQJCK5jEI7yooIKGcy0K3bMy023L9ora1BRalz1mT8lBvEgjWsAsEenfAEJPea5fqXwlOvNi2rbs2y8KLFaIO44ajaxfFzh0JAkYrcD0kFj1/rYVaGlWlJE0cbyRCkW22gYHpqmbQD7x1jty2kvUTEGAPAb2zL/vV6Jhei6aATWWO3Mv7P32A/YantknwLn08ZkFRvsJT1np5Yi3B31Mfq3VMP6uM4PcTbTQhOGaf38K3Qcl4kiYhs76f2soOSOljLnH1phwRuB3oNN1kpqtaUVhDHiCxILN7CZFNRwwRbUxZTyXKHfkljcE2Ux7rF/Jm8RUUSonYNigU0G3VjS4+6rwWSeWrd7ENk4TWDOqm6kqNngYYPwACymrFQUR6muZ2BNPlAWsUzSIepP6VEpelzwICthaBuL5saGysgTgLOvTUJDP9S9KOWWNC23Gc721kfMWKTAoiYGLaOwBtIRZHCWs4PC0d5u7scBr9ybyck+7PoqsaOO88QaVnHxvAkYb3wGSpbJiruPwSqt3Ro1x0YV18F12Cw3FOy7MRp66fRCNH/pVi//3jSTHo87tgwzuXz4Spufiy3que7LTiz0egocxTngQFvd3EV9Ua9CB8oFPcyTFLzPBlftK8ALf686gIwjId4gCasSUJi+B8B/Ws6T9+y7Ic8FAViOwE0LwHE2n8xC3ohbptHxsm+FwAalksWV/9KfGbZgBnW/6NBHhkgj4iruynSpa0MOO33sJNXCsFgUxtz4mCQtEv4XHnL+vhJwZwJyIG0MlvOOd1/mvfYTnw176shZfNEcJ6WYuTvAPwbEZBPN5/wsIXW56QyJPD/mjsYzfeKNIaO4jQUANZd5XuZZrt51p8JwT8Q1hpO8+A0aBAQl5u9tPJPuKFjEgdLuw5oEyFjjIftZE28XJTK00gF3HnV1FaNQc9QePzs248FMbIu+4htcwHlNuSoWCxA+WW+X2w1+ZJJu4khFJfutd+f9B7VpHXy2M15UiiWij3TE1WGcrB9sYz85bR/B9IAzVmnJMnmRRUpj8Huy2Ozxlgg99FL4fLoCBzV09lHmWqXxR9A2+jq/j4f3b4r9YQoO+jdJ6VOvoUBpn2Wmiunk6zrW53q7CcN4pjRNY3bqUOghFoUo2xnlkQhnEgXrEShK/4jsKcq95pkHyqRflf/LtJ0A49U6xvbiLsk2YDLFkYhQGEluB53Y47I+BGqNFWMzRxCNAdjSHqT/XI9+zce3mGApPuY4D45xqyRLRFO6oC9jlZd5zP5/XzpM8CKJEpSyoNkc4eRLPG/pNkyX+7uU2xDjqrjpsXFrs9TE/X0FJKA4tZBnH/WyRujRhgtN0JvVCbMiEFo/IOLZDOiEnZJnnxnT9qPq/RZEsKi/dcG7p02tpS7PBfsaeUudspYp9DXcRgoYNS++PpZLOcr06SEeHHih30I4xTvstsGY/NzOVVWRqyxGBaTwims7bmUPgKHJUUdGtIG6FzlrSV02Su9mYDqAYYL7UF14NEwiAdYqi7ff29TTgDamFy8JBEZN7JyXjfw9b2PXaEv6boFxl7HjpaazzlyZHnHari8+6Bc1xPmvuUFEUXI8+D1W3vjs7u8ZbWI8rPXzNQnN4KApVliELv2furaLVqGvVM8taBWZ2cFX+YVNGRGB0pFrfF3Lsb0Yvrv0lzHmg8S2DyHXxgsqKUQZIS2XI8YKIvnhccsJYiPFwRjo6/nVBdhdl19dD8FInJ8GBU4WoBc8ZPRIajM8C9ch5vqLw7UuvhmizI2DUH3fxyOQISIQb0zDhuHdpKSJ2IJmdvO3m0ff6lC8N58HSHj6J56H/NgQMUwMCFvS6kaKuIkewEAhfxDa15nIRLx5R0Y3kgwFWB0SkJb1FiW9pwRIw/++O05r9OeYxGBgGm+2SOxP2Varnoqtvosjg/kz,iv:gMyOIFvrfA4jHyEkMvG6lu1g+vlWLkNv9geA6K/1jgw=,tag:J4twaeghZ79/VJwkpAOMWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17zz5pz4u5h7jga6kvc7h6xad2uc9w6jhtjeu5kv8pv2t69p7xcwq6cezvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUkZjTmpQOGg5OFgwL05E
            Z1duRnlxb09ZNkEza0FnazRSeHNVWmxEblhzCnh5SU1COFVUbHlZMDlrai9TNzJx
            a0h3SWd5R2ZMcDdCSjY0WkdHZW1BRzgKLS0tIHNQL0NYR2hUYjJUVk1rbVQveHhC
            OHNaR2tzSjZwb3hJSzV3WTAwMVlKbVkKcxfqZEqZUglaM5MB4esJb3tL+E76VbqA
            6AxW7Db4+3hGZzM3774MMlJ1Vh4PyPdcjYo9q6j6EEPVTk3mOT9VsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T17:15:12Z"
    mac: ENC[AES256_GCM,data:LDOO1j4w5a6dLKDU+G3pnBo2uFR9SmeJ06YvmYvgr+gQNB1wZHi7MxA7Ur2l+OEolztUPmxHZxOtva8eHKDB077689T/NtGrexD4V6yvVJ4FLcIGgEaoPPPo5gLiBkGnRPgJBx2yyEmGkR3vIh4RQw7QGcIvavzTT3IYYEUdlig=,iv:1juxNd78y8pkw89fRbeI47McWz95O8RLjd/j1zlBcyg=,tag:hONwyoA7nzy3rVsr/i1hwA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.2
---
apiVersion: batch/v1
kind: CronJob
metadata:
    name: backup
    namespace: todoapp
spec:
    schedule: 0 0 * * *
    jobTemplate:
        spec:
            template:
                spec:
                    volumes:
                        - name: private-key-volume
                          configMap:
                            name: private-key-configmap
                            items:
                                - key: private-key.json
                                  path: private-key.json
                    containers:
                        - name: backup
                          image: your-backup-image:tag
                          env:
                            - name: POSTGRES_PASSWORD
                              valueFrom:
                                secretKeyRef:
                                    name: todoapp-postgres-key
                                    key: DB_PASSWORD
                            - name: URL
                              value: postgres://postgres:$(POSTGRES_PASSWORD)@postgres-svc:5432/postgres
                          volumeMounts:
                            - name: private-key-volume
                              mountPath: /usr/src/app/private-key.json
                              subPath: private-key.json
                          resources:
                            limits:
                              cpu: "100m"
                              memory: "100Mi"
                            requests:
                              cpu: "1m"
                              memory: "1Mi"
                    restartPolicy: OnFailure
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17zz5pz4u5h7jga6kvc7h6xad2uc9w6jhtjeu5kv8pv2t69p7xcwq6cezvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUkZjTmpQOGg5OFgwL05E
            Z1duRnlxb09ZNkEza0FnazRSeHNVWmxEblhzCnh5SU1COFVUbHlZMDlrai9TNzJx
            a0h3SWd5R2ZMcDdCSjY0WkdHZW1BRzgKLS0tIHNQL0NYR2hUYjJUVk1rbVQveHhC
            OHNaR2tzSjZwb3hJSzV3WTAwMVlKbVkKcxfqZEqZUglaM5MB4esJb3tL+E76VbqA
            6AxW7Db4+3hGZzM3774MMlJ1Vh4PyPdcjYo9q6j6EEPVTk3mOT9VsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T17:15:12Z"
    mac: ENC[AES256_GCM,data:LDOO1j4w5a6dLKDU+G3pnBo2uFR9SmeJ06YvmYvgr+gQNB1wZHi7MxA7Ur2l+OEolztUPmxHZxOtva8eHKDB077689T/NtGrexD4V6yvVJ4FLcIGgEaoPPPo5gLiBkGnRPgJBx2yyEmGkR3vIh4RQw7QGcIvavzTT3IYYEUdlig=,iv:1juxNd78y8pkw89fRbeI47McWz95O8RLjd/j1zlBcyg=,tag:hONwyoA7nzy3rVsr/i1hwA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.2
