apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
  namespace: todoapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: image
          persistentVolumeClaim:
            claimName: image-claim

      containers:
        - name: todo-app
          image: APP/IMAGE
          env:
          - name: PORT
            value: "3000"
          - name: BACKEND
            value: "http://backend-svc:2346/todos"
          volumeMounts:
          - name: image
            mountPath: /usr/src/app/image
          resources:
             limits:
               cpu: "100m"
               memory: "100Mi"

        - name: todo-backend
          image: BACKEND/IMAGE
          env:
          - name: PORT
            value: "3001"
          - name: PGHOST
            value: "postgres-svc"
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: todoapp-postgres-key
                key: DB_USERNAME
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: todoapp-postgres-key
                key: DB_PASSWORD
          resources:
             limits:
               cpu: "100m"
               memory: "100Mi"

        - name: image-generator
          image: STAMPGENERATOR/IMAGE
          volumeMounts:
          - name: image
            mountPath: /usr/src/app/image
          resources:
             limits:
               cpu: "100m"
               memory: "100Mi"