apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
  namespace: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim

      containers:
        - name: todo-app
          image: eeritvan/todo_app:latest
          env:
          - name: PORT
            value: "3000"
          - name: BACKEND
            value: "http://backend-svc:2346/todos"
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/image

        - name: todo-backend
          image: eeritvan/todo_backend:latest
          env:
          - name: PORT
            value: "3001"
          - name: PGHOST
            value: "postgres-svc"
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: todoapp-postgres-key
                key: DB_USERNAME
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: todoapp-postgres-key
                key: DB_PASSWORD

        - name: image-generator
          image: eeritvan/image_generator_app:latest
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/image