apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-pv
  namespace: todoapp
spec:
  storageClassName: image-pv 
  capacity:
    storage: 10Mi 
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity: 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0
