apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-claim
  namespace: todoapp
spec:
  storageClassName: image-pv 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi