name: Build and publish pingpong application

on:
  push:
    paths:
      - log output/**


jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish web_app
        working-directory: ./log output/web app
        run: |-
          docker build --tag "eeritvan/log_app:$GITHUB_SHA" .
          docker push "eeritvan/log_app:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        working-directory: ./log output
        run: kustomize edit set image LOGAPP/IMAGE=eeritvan/log_app:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: '"log output/kustomization.yaml"'
          message: New version released ${{ github.sha }}