name: Build and publish todoapp to production

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-publish:
    name: Build, Push, Release to production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish todo_app
        working-directory: ./todo application/
        run: |-
          docker build --tag "eeritvan/todo_app:$GITHUB_SHA" "./web app"
          docker push "eeritvan/todo_app:$GITHUB_SHA"

      - name: Build and publish todo_backend
        working-directory: ./todo application/
        run: |-
          docker build --tag "eeritvan/todo_backend:$GITHUB_SHA" "./todo-backend"
          docker push "eeritvan/todo_backend:$GITHUB_SHA"

      - name: Build and publish image_generator_app
        working-directory: ./todo application/
        run: |-
          docker build --tag "eeritvan/image_generator_app:$GITHUB_SHA" "./image_generator"
          docker push "eeritvan/image_generator_app:$GITHUB_SHA"

      - name: Build and publish daily_todo
        working-directory: ./todo application/
        run: |-
          docker build --tag "eeritvan/daily_todo:$GITHUB_SHA" "./daily_todo"
          docker push "eeritvan/daily_todo:$GITHUB_SHA"

      - name: Build and publish todo_backup
        working-directory: ./todo application/
        run: |-
          docker build --tag "eeritvan/todo_backup:$GITHUB_SHA" "./todo_backup"
          docker push "eeritvan/todo_backup:$GITHUB_SHA"

      - name: Build and publish broadcast
        working-directory: ./todo application/
        run: |-
          docker build --tag "eeritvan/broadcast:$GITHUB_SHA" "./broadcaster"
          docker push "eeritvan/broadcast:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right images
        working-directory: ./todo application/overlays/production
        run: |-
          kustomize edit set image APP/IMAGE=eeritvan/todo_app:$GITHUB_SHA
          kustomize edit set image BACKEND/IMAGE=eeritvan/todo_backend:$GITHUB_SHA
          kustomize edit set image STAMPGENERATOR/IMAGE=eeritvan/image_generator_app:$GITHUB_SHA
          kustomize edit set image DAILYTODO/IMAGE=eeritvan/daily_todo:$GITHUB_SHA
          kustomize edit set image BACKUPBD/IMAGE=eeritvan/todo_backup:$GITHUB_SHA
          kustomize edit set image BROADCAST/IMAGE=eeritvan/broadcast:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: '"todo application/kustomization.yaml"'
          message: New version released ${{ github.sha }}