name: Build and publish todoapp to staging

on:
  push:
    branches:
      - master
    paths:
      - todo application/**

jobs:
  build-publish:
    name: Build, Push, Release to stagings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish 
        working-directory: ./log output/
        run: |-
          docker build --tag "eeritvan/todo_app:$GITHUB_SHA" .
          docker build --tag "eeritvan/todo_backend:$GITHUB_SHA" .
          docker build --tag "eeritvan/image_generator_app:$GITHUB_SHA" .
          docker build --tag "eeritvan/daily_todo:$GITHUB_SHA" .
          docker build --tag "eeritvan/todo_backup:$GITHUB_SHA" .
          docker build --tag "eeritvan/broadcast:$GITHUB_SHA" .
          docker push "eeritvan/todo_app:$GITHUB_SHA"
          docker push "eeritvan/todo_backend:$GITHUB_SHA"
          docker push "eeritvan/image_generator_app:$GITHUB_SHA"
          docker push "eeritvan/daily_todo:$GITHUB_SHA"
          docker push "eeritvan/todo_backup:$GITHUB_SHA"
          docker push "eeritvan/broadcast:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right images
        working-directory: ./todo application/overlays/staging
        run: |-
          kustomize edit set image APP/IMAGE=eeritvan/todo_app:$GITHUB_SHA
          kustomize edit set image BACKEND/IMAGE=eeritvan/todo_backend:$GITHUB_SHA
          kustomize edit set image STAMPGENERATOR/IMAGE=eeritvan/image_generator_app:$GITHUB_SHA
          kustomize edit set image DAILYTODO/IMAGE=eeritvan/daily_todo:$GITHUB_SHA
          kustomize edit set image BACKUPBD/IMAGE=eeritvan/todo_backup:$GITHUB_SHA
          kustomize edit set image BROADCAST/IMAGE=eeritvan/broadcast:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: '"todo application/kustomization.yaml"'
          message: New version released ${{ github.sha }}